# Generated by Django 2.0.7 on 2018-07-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='slug',
        ),
    ]
